# Generated by Django 4.0.4 on 2022-05-27 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_list_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='UserList',
        ),
    ]
